### ISSUE TITLE
No license specified

### ISSUE THREAD

**Issue by scott-moxham** [davidfowl/AspireSwaggerUI#6]
I can't see any license specified for this project, either in GitHub or in the source files.

I'd like to try using this in my project but need to know what license it is first, so I don't get clobbered by an onerous requirement, e.g. requiring me to make all my code open source.

Can you specify a license of some sort?

**Comment by davidfowl** [comment]
There you go https://github.com/davidfowl/AspireSwaggerUI/blob/main/LICENSE

**Comment by scott-moxham** [comment]
Brilliant

Thanks David.
I wasn't expecting such a quick response 🙂



Thanks

Scott

________________________________
